//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WS_MiMetaBG.WsCashBVBGMail_BG {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceMSGSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceMSG : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviarMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMail1OperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMail2OperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMailSeguroOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMailSeguro1OperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMailCTOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarSMSccOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarSMSwPOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarSMS2OperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMailPlantillaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMailPlantillaMuchosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMailPlantillaMuchosAdjuntosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMailConAdjuntosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMailConAdjuntos1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMailPlantillaBancontrolOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarMailPlantillaAdjuntoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarNotificacionesPushOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceMSG() {
            this.Url = global::WS_MiMetaBG.Properties.Settings.Default.WS_MiMetaBG_WsCashBVBGMail_BG_WebServiceMSG;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnviarMailCompletedEventHandler EnviarMailCompleted;
        
        /// <remarks/>
        public event EnviarMail1CompletedEventHandler EnviarMail1Completed;
        
        /// <remarks/>
        public event EnviarMail2CompletedEventHandler EnviarMail2Completed;
        
        /// <remarks/>
        public event EnviarMailSeguroCompletedEventHandler EnviarMailSeguroCompleted;
        
        /// <remarks/>
        public event EnviarMailSeguro1CompletedEventHandler EnviarMailSeguro1Completed;
        
        /// <remarks/>
        public event EnviarMailCTCompletedEventHandler EnviarMailCTCompleted;
        
        /// <remarks/>
        public event EnviarSMSccCompletedEventHandler EnviarSMSccCompleted;
        
        /// <remarks/>
        public event EnviarSMSwPCompletedEventHandler EnviarSMSwPCompleted;
        
        /// <remarks/>
        public event EnviarSMS2CompletedEventHandler EnviarSMS2Completed;
        
        /// <remarks/>
        public event EnviarSMSCompletedEventHandler EnviarSMSCompleted;
        
        /// <remarks/>
        public event EnviarMailPlantillaCompletedEventHandler EnviarMailPlantillaCompleted;
        
        /// <remarks/>
        public event EnviarMailPlantillaMuchosCompletedEventHandler EnviarMailPlantillaMuchosCompleted;
        
        /// <remarks/>
        public event EnviarMailPlantillaMuchosAdjuntosCompletedEventHandler EnviarMailPlantillaMuchosAdjuntosCompleted;
        
        /// <remarks/>
        public event EnviarMailConAdjuntosCompletedEventHandler EnviarMailConAdjuntosCompleted;
        
        /// <remarks/>
        public event EnviarMailConAdjuntos1CompletedEventHandler EnviarMailConAdjuntos1Completed;
        
        /// <remarks/>
        public event ConsultaFacturaCompletedEventHandler ConsultaFacturaCompleted;
        
        /// <remarks/>
        public event EnviarMailPlantillaBancontrolCompletedEventHandler EnviarMailPlantillaBancontrolCompleted;
        
        /// <remarks/>
        public event EnviarMailPlantillaAdjuntoCompletedEventHandler EnviarMailPlantillaAdjuntoCompleted;
        
        /// <remarks/>
        public event EnviarNotificacionesPushCompletedEventHandler EnviarNotificacionesPushCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarMail(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] _adjunto) {
            object[] results = this.Invoke("EnviarMail", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        _adjunto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, byte[] _adjunto) {
            this.EnviarMailAsync(_de, _para, _copia, _asunto, _mensaje, _nombreAdjunto, _adjunto, null);
        }
        
        /// <remarks/>
        public void EnviarMailAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, byte[] _adjunto, object userState) {
            if ((this.EnviarMailOperationCompleted == null)) {
                this.EnviarMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailOperationCompleted);
            }
            this.InvokeAsync("EnviarMail", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        _adjunto}, this.EnviarMailOperationCompleted, userState);
        }
        
        private void OnEnviarMailOperationCompleted(object arg) {
            if ((this.EnviarMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailCompleted(this, new EnviarMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="EnviarMail1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailServidor", RequestElementName="EnviarMailServidor", RequestNamespace="http://tempuri.org/", ResponseElementName="EnviarMailServidorResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("EnviarMailServidorResult")]
        public string EnviarMail(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] _adjunto, string _srvMail) {
            object[] results = this.Invoke("EnviarMail1", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        _adjunto,
                        _srvMail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMail1Async(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, byte[] _adjunto, string _srvMail) {
            this.EnviarMail1Async(_de, _para, _copia, _asunto, _mensaje, _nombreAdjunto, _adjunto, _srvMail, null);
        }
        
        /// <remarks/>
        public void EnviarMail1Async(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, byte[] _adjunto, string _srvMail, object userState) {
            if ((this.EnviarMail1OperationCompleted == null)) {
                this.EnviarMail1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMail1OperationCompleted);
            }
            this.InvokeAsync("EnviarMail1", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        _adjunto,
                        _srvMail}, this.EnviarMail1OperationCompleted, userState);
        }
        
        private void OnEnviarMail1OperationCompleted(object arg) {
            if ((this.EnviarMail1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMail1Completed(this, new EnviarMail1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMail2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarMail2(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, int iLinea) {
            object[] results = this.Invoke("EnviarMail2", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        iLinea});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMail2Async(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, int iLinea) {
            this.EnviarMail2Async(_de, _para, _copia, _asunto, _mensaje, _nombreAdjunto, iLinea, null);
        }
        
        /// <remarks/>
        public void EnviarMail2Async(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, int iLinea, object userState) {
            if ((this.EnviarMail2OperationCompleted == null)) {
                this.EnviarMail2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMail2OperationCompleted);
            }
            this.InvokeAsync("EnviarMail2", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        iLinea}, this.EnviarMail2OperationCompleted, userState);
        }
        
        private void OnEnviarMail2OperationCompleted(object arg) {
            if ((this.EnviarMail2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMail2Completed(this, new EnviarMail2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailSeguro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarMailSeguro(string de, string nombreDe, string para, string nombrePara, string copia, string asunto, string mensajeHtml, string nombreImagen) {
            object[] results = this.Invoke("EnviarMailSeguro", new object[] {
                        de,
                        nombreDe,
                        para,
                        nombrePara,
                        copia,
                        asunto,
                        mensajeHtml,
                        nombreImagen});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailSeguroAsync(string de, string nombreDe, string para, string nombrePara, string copia, string asunto, string mensajeHtml, string nombreImagen) {
            this.EnviarMailSeguroAsync(de, nombreDe, para, nombrePara, copia, asunto, mensajeHtml, nombreImagen, null);
        }
        
        /// <remarks/>
        public void EnviarMailSeguroAsync(string de, string nombreDe, string para, string nombrePara, string copia, string asunto, string mensajeHtml, string nombreImagen, object userState) {
            if ((this.EnviarMailSeguroOperationCompleted == null)) {
                this.EnviarMailSeguroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailSeguroOperationCompleted);
            }
            this.InvokeAsync("EnviarMailSeguro", new object[] {
                        de,
                        nombreDe,
                        para,
                        nombrePara,
                        copia,
                        asunto,
                        mensajeHtml,
                        nombreImagen}, this.EnviarMailSeguroOperationCompleted, userState);
        }
        
        private void OnEnviarMailSeguroOperationCompleted(object arg) {
            if ((this.EnviarMailSeguroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailSeguroCompleted(this, new EnviarMailSeguroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="EnviarMailSeguro1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailSeguroServidor", RequestElementName="EnviarMailSeguroServidor", RequestNamespace="http://tempuri.org/", ResponseElementName="EnviarMailSeguroServidorResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("EnviarMailSeguroServidorResult")]
        public string EnviarMailSeguro(string de, string nombreDe, string para, string nombrePara, string copia, string asunto, string mensajeHtml, string nombreImagen, string srvMail) {
            object[] results = this.Invoke("EnviarMailSeguro1", new object[] {
                        de,
                        nombreDe,
                        para,
                        nombrePara,
                        copia,
                        asunto,
                        mensajeHtml,
                        nombreImagen,
                        srvMail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailSeguro1Async(string de, string nombreDe, string para, string nombrePara, string copia, string asunto, string mensajeHtml, string nombreImagen, string srvMail) {
            this.EnviarMailSeguro1Async(de, nombreDe, para, nombrePara, copia, asunto, mensajeHtml, nombreImagen, srvMail, null);
        }
        
        /// <remarks/>
        public void EnviarMailSeguro1Async(string de, string nombreDe, string para, string nombrePara, string copia, string asunto, string mensajeHtml, string nombreImagen, string srvMail, object userState) {
            if ((this.EnviarMailSeguro1OperationCompleted == null)) {
                this.EnviarMailSeguro1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailSeguro1OperationCompleted);
            }
            this.InvokeAsync("EnviarMailSeguro1", new object[] {
                        de,
                        nombreDe,
                        para,
                        nombrePara,
                        copia,
                        asunto,
                        mensajeHtml,
                        nombreImagen,
                        srvMail}, this.EnviarMailSeguro1OperationCompleted, userState);
        }
        
        private void OnEnviarMailSeguro1OperationCompleted(object arg) {
            if ((this.EnviarMailSeguro1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailSeguro1Completed(this, new EnviarMailSeguro1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailCT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarMailCT(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] _adjunto, string _contentType) {
            object[] results = this.Invoke("EnviarMailCT", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        _adjunto,
                        _contentType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailCTAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, byte[] _adjunto, string _contentType) {
            this.EnviarMailCTAsync(_de, _para, _copia, _asunto, _mensaje, _nombreAdjunto, _adjunto, _contentType, null);
        }
        
        /// <remarks/>
        public void EnviarMailCTAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, byte[] _adjunto, string _contentType, object userState) {
            if ((this.EnviarMailCTOperationCompleted == null)) {
                this.EnviarMailCTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailCTOperationCompleted);
            }
            this.InvokeAsync("EnviarMailCT", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        _adjunto,
                        _contentType}, this.EnviarMailCTOperationCompleted, userState);
        }
        
        private void OnEnviarMailCTOperationCompleted(object arg) {
            if ((this.EnviarMailCTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailCTCompleted(this, new EnviarMailCTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarSMScc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarSMScc(string _para, string _mensaje, string _opid, string _origen, string _comando, string _codigo) {
            object[] results = this.Invoke("EnviarSMScc", new object[] {
                        _para,
                        _mensaje,
                        _opid,
                        _origen,
                        _comando,
                        _codigo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarSMSccAsync(string _para, string _mensaje, string _opid, string _origen, string _comando, string _codigo) {
            this.EnviarSMSccAsync(_para, _mensaje, _opid, _origen, _comando, _codigo, null);
        }
        
        /// <remarks/>
        public void EnviarSMSccAsync(string _para, string _mensaje, string _opid, string _origen, string _comando, string _codigo, object userState) {
            if ((this.EnviarSMSccOperationCompleted == null)) {
                this.EnviarSMSccOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarSMSccOperationCompleted);
            }
            this.InvokeAsync("EnviarSMScc", new object[] {
                        _para,
                        _mensaje,
                        _opid,
                        _origen,
                        _comando,
                        _codigo}, this.EnviarSMSccOperationCompleted, userState);
        }
        
        private void OnEnviarSMSccOperationCompleted(object arg) {
            if ((this.EnviarSMSccCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarSMSccCompleted(this, new EnviarSMSccCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarSMSwP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarSMSwP(string _para, string _mensaje, string _opid, string _origen, string _params) {
            object[] results = this.Invoke("EnviarSMSwP", new object[] {
                        _para,
                        _mensaje,
                        _opid,
                        _origen,
                        _params});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarSMSwPAsync(string _para, string _mensaje, string _opid, string _origen, string _params) {
            this.EnviarSMSwPAsync(_para, _mensaje, _opid, _origen, _params, null);
        }
        
        /// <remarks/>
        public void EnviarSMSwPAsync(string _para, string _mensaje, string _opid, string _origen, string _params, object userState) {
            if ((this.EnviarSMSwPOperationCompleted == null)) {
                this.EnviarSMSwPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarSMSwPOperationCompleted);
            }
            this.InvokeAsync("EnviarSMSwP", new object[] {
                        _para,
                        _mensaje,
                        _opid,
                        _origen,
                        _params}, this.EnviarSMSwPOperationCompleted, userState);
        }
        
        private void OnEnviarSMSwPOperationCompleted(object arg) {
            if ((this.EnviarSMSwPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarSMSwPCompleted(this, new EnviarSMSwPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarSMS2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarSMS2(string _para, string _mensaje, string _opid, string _origen) {
            object[] results = this.Invoke("EnviarSMS2", new object[] {
                        _para,
                        _mensaje,
                        _opid,
                        _origen});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarSMS2Async(string _para, string _mensaje, string _opid, string _origen) {
            this.EnviarSMS2Async(_para, _mensaje, _opid, _origen, null);
        }
        
        /// <remarks/>
        public void EnviarSMS2Async(string _para, string _mensaje, string _opid, string _origen, object userState) {
            if ((this.EnviarSMS2OperationCompleted == null)) {
                this.EnviarSMS2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarSMS2OperationCompleted);
            }
            this.InvokeAsync("EnviarSMS2", new object[] {
                        _para,
                        _mensaje,
                        _opid,
                        _origen}, this.EnviarSMS2OperationCompleted, userState);
        }
        
        private void OnEnviarSMS2OperationCompleted(object arg) {
            if ((this.EnviarSMS2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarSMS2Completed(this, new EnviarSMS2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarSMS(string _para, string _mensaje, string _opid) {
            object[] results = this.Invoke("EnviarSMS", new object[] {
                        _para,
                        _mensaje,
                        _opid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarSMSAsync(string _para, string _mensaje, string _opid) {
            this.EnviarSMSAsync(_para, _mensaje, _opid, null);
        }
        
        /// <remarks/>
        public void EnviarSMSAsync(string _para, string _mensaje, string _opid, object userState) {
            if ((this.EnviarSMSOperationCompleted == null)) {
                this.EnviarSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarSMSOperationCompleted);
            }
            this.InvokeAsync("EnviarSMS", new object[] {
                        _para,
                        _mensaje,
                        _opid}, this.EnviarSMSOperationCompleted, userState);
        }
        
        private void OnEnviarSMSOperationCompleted(object arg) {
            if ((this.EnviarSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarSMSCompleted(this, new EnviarSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailPlantilla", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarMailPlantilla(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, int iLinea) {
            object[] results = this.Invoke("EnviarMailPlantilla", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        iLinea});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailPlantillaAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, int iLinea) {
            this.EnviarMailPlantillaAsync(_de, _para, _copia, _asunto, _mensaje, _nombreAdjunto, iLinea, null);
        }
        
        /// <remarks/>
        public void EnviarMailPlantillaAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, int iLinea, object userState) {
            if ((this.EnviarMailPlantillaOperationCompleted == null)) {
                this.EnviarMailPlantillaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailPlantillaOperationCompleted);
            }
            this.InvokeAsync("EnviarMailPlantilla", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        iLinea}, this.EnviarMailPlantillaOperationCompleted, userState);
        }
        
        private void OnEnviarMailPlantillaOperationCompleted(object arg) {
            if ((this.EnviarMailPlantillaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailPlantillaCompleted(this, new EnviarMailPlantillaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailPlantillaMuchos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarMailPlantillaMuchos(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nomArchivoAd, string rutaArchivoAd, int iLinea) {
            object[] results = this.Invoke("EnviarMailPlantillaMuchos", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nomArchivoAd,
                        rutaArchivoAd,
                        iLinea});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailPlantillaMuchosAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nomArchivoAd, string rutaArchivoAd, int iLinea) {
            this.EnviarMailPlantillaMuchosAsync(_de, _para, _copia, _asunto, _mensaje, _nomArchivoAd, rutaArchivoAd, iLinea, null);
        }
        
        /// <remarks/>
        public void EnviarMailPlantillaMuchosAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nomArchivoAd, string rutaArchivoAd, int iLinea, object userState) {
            if ((this.EnviarMailPlantillaMuchosOperationCompleted == null)) {
                this.EnviarMailPlantillaMuchosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailPlantillaMuchosOperationCompleted);
            }
            this.InvokeAsync("EnviarMailPlantillaMuchos", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nomArchivoAd,
                        rutaArchivoAd,
                        iLinea}, this.EnviarMailPlantillaMuchosOperationCompleted, userState);
        }
        
        private void OnEnviarMailPlantillaMuchosOperationCompleted(object arg) {
            if ((this.EnviarMailPlantillaMuchosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailPlantillaMuchosCompleted(this, new EnviarMailPlantillaMuchosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailPlantillaMuchosAdjuntos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarMailPlantillaMuchosAdjuntos(string _de, string _para, string _copia, string _asunto, string _mensaje, int iLinea, ArchivoAdjunto[] archivosAdjuntos) {
            object[] results = this.Invoke("EnviarMailPlantillaMuchosAdjuntos", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        iLinea,
                        archivosAdjuntos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailPlantillaMuchosAdjuntosAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, int iLinea, ArchivoAdjunto[] archivosAdjuntos) {
            this.EnviarMailPlantillaMuchosAdjuntosAsync(_de, _para, _copia, _asunto, _mensaje, iLinea, archivosAdjuntos, null);
        }
        
        /// <remarks/>
        public void EnviarMailPlantillaMuchosAdjuntosAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, int iLinea, ArchivoAdjunto[] archivosAdjuntos, object userState) {
            if ((this.EnviarMailPlantillaMuchosAdjuntosOperationCompleted == null)) {
                this.EnviarMailPlantillaMuchosAdjuntosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailPlantillaMuchosAdjuntosOperationCompleted);
            }
            this.InvokeAsync("EnviarMailPlantillaMuchosAdjuntos", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        iLinea,
                        archivosAdjuntos}, this.EnviarMailPlantillaMuchosAdjuntosOperationCompleted, userState);
        }
        
        private void OnEnviarMailPlantillaMuchosAdjuntosOperationCompleted(object arg) {
            if ((this.EnviarMailPlantillaMuchosAdjuntosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailPlantillaMuchosAdjuntosCompleted(this, new EnviarMailPlantillaMuchosAdjuntosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailConAdjuntos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarMailConAdjuntos(string de, string para, string copia, string asunto, string mensaje, ArchivoAdjunto[] archivosAdjuntos) {
            object[] results = this.Invoke("EnviarMailConAdjuntos", new object[] {
                        de,
                        para,
                        copia,
                        asunto,
                        mensaje,
                        archivosAdjuntos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailConAdjuntosAsync(string de, string para, string copia, string asunto, string mensaje, ArchivoAdjunto[] archivosAdjuntos) {
            this.EnviarMailConAdjuntosAsync(de, para, copia, asunto, mensaje, archivosAdjuntos, null);
        }
        
        /// <remarks/>
        public void EnviarMailConAdjuntosAsync(string de, string para, string copia, string asunto, string mensaje, ArchivoAdjunto[] archivosAdjuntos, object userState) {
            if ((this.EnviarMailConAdjuntosOperationCompleted == null)) {
                this.EnviarMailConAdjuntosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailConAdjuntosOperationCompleted);
            }
            this.InvokeAsync("EnviarMailConAdjuntos", new object[] {
                        de,
                        para,
                        copia,
                        asunto,
                        mensaje,
                        archivosAdjuntos}, this.EnviarMailConAdjuntosOperationCompleted, userState);
        }
        
        private void OnEnviarMailConAdjuntosOperationCompleted(object arg) {
            if ((this.EnviarMailConAdjuntosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailConAdjuntosCompleted(this, new EnviarMailConAdjuntosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="EnviarMailConAdjuntos1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailConAdjuntosServidor", RequestElementName="EnviarMailConAdjuntosServidor", RequestNamespace="http://tempuri.org/", ResponseElementName="EnviarMailConAdjuntosServidorResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("EnviarMailConAdjuntosServidorResult")]
        public string EnviarMailConAdjuntos(string de, string para, string copia, string asunto, string mensaje, ArchivoAdjunto[] archivosAdjuntos, string srvMail) {
            object[] results = this.Invoke("EnviarMailConAdjuntos1", new object[] {
                        de,
                        para,
                        copia,
                        asunto,
                        mensaje,
                        archivosAdjuntos,
                        srvMail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailConAdjuntos1Async(string de, string para, string copia, string asunto, string mensaje, ArchivoAdjunto[] archivosAdjuntos, string srvMail) {
            this.EnviarMailConAdjuntos1Async(de, para, copia, asunto, mensaje, archivosAdjuntos, srvMail, null);
        }
        
        /// <remarks/>
        public void EnviarMailConAdjuntos1Async(string de, string para, string copia, string asunto, string mensaje, ArchivoAdjunto[] archivosAdjuntos, string srvMail, object userState) {
            if ((this.EnviarMailConAdjuntos1OperationCompleted == null)) {
                this.EnviarMailConAdjuntos1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailConAdjuntos1OperationCompleted);
            }
            this.InvokeAsync("EnviarMailConAdjuntos1", new object[] {
                        de,
                        para,
                        copia,
                        asunto,
                        mensaje,
                        archivosAdjuntos,
                        srvMail}, this.EnviarMailConAdjuntos1OperationCompleted, userState);
        }
        
        private void OnEnviarMailConAdjuntos1OperationCompleted(object arg) {
            if ((this.EnviarMailConAdjuntos1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailConAdjuntos1Completed(this, new EnviarMailConAdjuntos1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaFactura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MsgRpConsultaFacturas ConsultaFactura(string ClienteTJ, string Usuario, string estacion) {
            object[] results = this.Invoke("ConsultaFactura", new object[] {
                        ClienteTJ,
                        Usuario,
                        estacion});
            return ((MsgRpConsultaFacturas)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaFacturaAsync(string ClienteTJ, string Usuario, string estacion) {
            this.ConsultaFacturaAsync(ClienteTJ, Usuario, estacion, null);
        }
        
        /// <remarks/>
        public void ConsultaFacturaAsync(string ClienteTJ, string Usuario, string estacion, object userState) {
            if ((this.ConsultaFacturaOperationCompleted == null)) {
                this.ConsultaFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaFacturaOperationCompleted);
            }
            this.InvokeAsync("ConsultaFactura", new object[] {
                        ClienteTJ,
                        Usuario,
                        estacion}, this.ConsultaFacturaOperationCompleted, userState);
        }
        
        private void OnConsultaFacturaOperationCompleted(object arg) {
            if ((this.ConsultaFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaFacturaCompleted(this, new ConsultaFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailPlantillaBancontrol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarMailPlantillaBancontrol(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] _archivoAdjunto) {
            object[] results = this.Invoke("EnviarMailPlantillaBancontrol", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        _archivoAdjunto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailPlantillaBancontrolAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, byte[] _archivoAdjunto) {
            this.EnviarMailPlantillaBancontrolAsync(_de, _para, _copia, _asunto, _mensaje, _nombreAdjunto, _archivoAdjunto, null);
        }
        
        /// <remarks/>
        public void EnviarMailPlantillaBancontrolAsync(string _de, string _para, string _copia, string _asunto, string _mensaje, string _nombreAdjunto, byte[] _archivoAdjunto, object userState) {
            if ((this.EnviarMailPlantillaBancontrolOperationCompleted == null)) {
                this.EnviarMailPlantillaBancontrolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailPlantillaBancontrolOperationCompleted);
            }
            this.InvokeAsync("EnviarMailPlantillaBancontrol", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        _mensaje,
                        _nombreAdjunto,
                        _archivoAdjunto}, this.EnviarMailPlantillaBancontrolOperationCompleted, userState);
        }
        
        private void OnEnviarMailPlantillaBancontrolOperationCompleted(object arg) {
            if ((this.EnviarMailPlantillaBancontrolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailPlantillaBancontrolCompleted(this, new EnviarMailPlantillaBancontrolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMailPlantillaAdjunto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarMailPlantillaAdjunto(string _de, string _para, string _copia, string _asunto, string nombreplantilla, string XmlpathVar, ArchivoAdjunto[] archivosAdjuntos) {
            object[] results = this.Invoke("EnviarMailPlantillaAdjunto", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        nombreplantilla,
                        XmlpathVar,
                        archivosAdjuntos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarMailPlantillaAdjuntoAsync(string _de, string _para, string _copia, string _asunto, string nombreplantilla, string XmlpathVar, ArchivoAdjunto[] archivosAdjuntos) {
            this.EnviarMailPlantillaAdjuntoAsync(_de, _para, _copia, _asunto, nombreplantilla, XmlpathVar, archivosAdjuntos, null);
        }
        
        /// <remarks/>
        public void EnviarMailPlantillaAdjuntoAsync(string _de, string _para, string _copia, string _asunto, string nombreplantilla, string XmlpathVar, ArchivoAdjunto[] archivosAdjuntos, object userState) {
            if ((this.EnviarMailPlantillaAdjuntoOperationCompleted == null)) {
                this.EnviarMailPlantillaAdjuntoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarMailPlantillaAdjuntoOperationCompleted);
            }
            this.InvokeAsync("EnviarMailPlantillaAdjunto", new object[] {
                        _de,
                        _para,
                        _copia,
                        _asunto,
                        nombreplantilla,
                        XmlpathVar,
                        archivosAdjuntos}, this.EnviarMailPlantillaAdjuntoOperationCompleted, userState);
        }
        
        private void OnEnviarMailPlantillaAdjuntoOperationCompleted(object arg) {
            if ((this.EnviarMailPlantillaAdjuntoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarMailPlantillaAdjuntoCompleted(this, new EnviarMailPlantillaAdjuntoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarNotificacionesPush", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NotificacionPushOut EnviarNotificacionesPush(NotificacionPush notificaPushIn) {
            object[] results = this.Invoke("EnviarNotificacionesPush", new object[] {
                        notificaPushIn});
            return ((NotificacionPushOut)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarNotificacionesPushAsync(NotificacionPush notificaPushIn) {
            this.EnviarNotificacionesPushAsync(notificaPushIn, null);
        }
        
        /// <remarks/>
        public void EnviarNotificacionesPushAsync(NotificacionPush notificaPushIn, object userState) {
            if ((this.EnviarNotificacionesPushOperationCompleted == null)) {
                this.EnviarNotificacionesPushOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarNotificacionesPushOperationCompleted);
            }
            this.InvokeAsync("EnviarNotificacionesPush", new object[] {
                        notificaPushIn}, this.EnviarNotificacionesPushOperationCompleted, userState);
        }
        
        private void OnEnviarNotificacionesPushOperationCompleted(object arg) {
            if ((this.EnviarNotificacionesPushCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarNotificacionesPushCompleted(this, new EnviarNotificacionesPushCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ArchivoAdjunto {
        
        private string nombreField;
        
        private byte[] contenidoField;
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NotificacionPushOut {
        
        private int codigoRetornoField;
        
        private string mensajeRetornoField;
        
        /// <comentarios/>
        public int CodigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <comentarios/>
        public string MensajeRetorno {
            get {
                return this.mensajeRetornoField;
            }
            set {
                this.mensajeRetornoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetallePush {
        
        private string tituloField;
        
        private string mensajeField;
        
        private string nombreCortoField;
        
        private string idPushField;
        
        /// <comentarios/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreCorto {
            get {
                return this.nombreCortoField;
            }
            set {
                this.nombreCortoField = value;
            }
        }
        
        /// <comentarios/>
        public string IdPush {
            get {
                return this.idPushField;
            }
            set {
                this.idPushField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CabeceraPush {
        
        private bool todosField;
        
        private string tituloField;
        
        private string mensajeField;
        
        /// <comentarios/>
        public bool Todos {
            get {
                return this.todosField;
            }
            set {
                this.todosField = value;
            }
        }
        
        /// <comentarios/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NotificacionPush {
        
        private CabeceraPush cabeceraField;
        
        private DetallePush[] detalleField;
        
        /// <comentarios/>
        public CabeceraPush Cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
            }
        }
        
        /// <comentarios/>
        public DetallePush[] Detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MensajesWs.MsgConsultaFacturas")]
    public partial class MsgConsultaFacturas {
        
        private string fVencidoField;
        
        private string facturaField;
        
        private string detallistaField;
        
        private string fEmisionField;
        
        private double vPagarField;
        
        private string nombreDistribuidorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FVencido {
            get {
                return this.fVencidoField;
            }
            set {
                this.fVencidoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Detallista {
            get {
                return this.detallistaField;
            }
            set {
                this.detallistaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FEmision {
            get {
                return this.fEmisionField;
            }
            set {
                this.fEmisionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double VPagar {
            get {
                return this.vPagarField;
            }
            set {
                this.vPagarField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NombreDistribuidor {
            get {
                return this.nombreDistribuidorField;
            }
            set {
                this.nombreDistribuidorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MensajesWs.MsgCabResponse")]
    public partial class MsgCabResponse {
        
        private int numFilasField;
        
        private string codRespuestaField;
        
        private string mensajeField;
        
        private string statusField;
        
        private string printsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NumFilas {
            get {
                return this.numFilasField;
            }
            set {
                this.numFilasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodRespuesta {
            get {
                return this.codRespuestaField;
            }
            set {
                this.codRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Prints {
            get {
                return this.printsField;
            }
            set {
                this.printsField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MensajesWs.MsgRpConsultaFacturas")]
    public partial class MsgRpConsultaFacturas {
        
        private MsgCabResponse cabeceraField;
        
        private MsgConsultaFacturas[] consultaFacturasField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MsgCabResponse Cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultaFacturas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MsgConsultaFacturas[] ConsultaFacturas {
            get {
                return this.consultaFacturasField;
            }
            set {
                this.consultaFacturasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailCompletedEventHandler(object sender, EnviarMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMail1CompletedEventHandler(object sender, EnviarMail1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMail1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMail1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMail2CompletedEventHandler(object sender, EnviarMail2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMail2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMail2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailSeguroCompletedEventHandler(object sender, EnviarMailSeguroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailSeguroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailSeguroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailSeguro1CompletedEventHandler(object sender, EnviarMailSeguro1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailSeguro1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailSeguro1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailCTCompletedEventHandler(object sender, EnviarMailCTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailCTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailCTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarSMSccCompletedEventHandler(object sender, EnviarSMSccCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarSMSccCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarSMSccCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarSMSwPCompletedEventHandler(object sender, EnviarSMSwPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarSMSwPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarSMSwPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarSMS2CompletedEventHandler(object sender, EnviarSMS2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarSMS2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarSMS2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarSMSCompletedEventHandler(object sender, EnviarSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailPlantillaCompletedEventHandler(object sender, EnviarMailPlantillaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailPlantillaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailPlantillaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailPlantillaMuchosCompletedEventHandler(object sender, EnviarMailPlantillaMuchosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailPlantillaMuchosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailPlantillaMuchosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailPlantillaMuchosAdjuntosCompletedEventHandler(object sender, EnviarMailPlantillaMuchosAdjuntosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailPlantillaMuchosAdjuntosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailPlantillaMuchosAdjuntosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailConAdjuntosCompletedEventHandler(object sender, EnviarMailConAdjuntosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailConAdjuntosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailConAdjuntosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailConAdjuntos1CompletedEventHandler(object sender, EnviarMailConAdjuntos1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailConAdjuntos1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailConAdjuntos1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ConsultaFacturaCompletedEventHandler(object sender, ConsultaFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsgRpConsultaFacturas Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsgRpConsultaFacturas)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailPlantillaBancontrolCompletedEventHandler(object sender, EnviarMailPlantillaBancontrolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailPlantillaBancontrolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailPlantillaBancontrolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarMailPlantillaAdjuntoCompletedEventHandler(object sender, EnviarMailPlantillaAdjuntoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarMailPlantillaAdjuntoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarMailPlantillaAdjuntoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnviarNotificacionesPushCompletedEventHandler(object sender, EnviarNotificacionesPushCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarNotificacionesPushCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarNotificacionesPushCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NotificacionPushOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NotificacionPushOut)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591