//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_MiMetaBG.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.26.60.56:8088/EntrustInterfaceWS/FuncionesExt.asmx")]
        public string WS_MiMetaBG_WsEntrust_BG_FuncionesExt {
            get {
                return ((string)(this["WS_MiMetaBG_WsEntrust_BG_FuncionesExt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.26.60.71:88/BG.Neo.Ws.Persona/Personas.asmx")]
        public string WS_MiMetaBG_WsPersona_BG_Personas {
            get {
                return ((string)(this["WS_MiMetaBG_WsPersona_BG_Personas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.26.60.165:88/BG.AvisoSeguro.Notificaciones.WS/NotificacionesService.as" +
            "mx")]
        public string WS_MiMetaBG_WsAvisoSeguro_BG_NotificacionesService {
            get {
                return ((string)(this["WS_MiMetaBG_WsAvisoSeguro_BG_NotificacionesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.26.60.56/BG.CashBVBG.WS/WebServiceBG.asmx")]
        public string WS_MiMetaBG_WsCashBV_BG_WebServiceBG {
            get {
                return ((string)(this["WS_MiMetaBG_WsCashBV_BG_WebServiceBG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.26.60.56/BG.CashBVBG.WS/WebServiceMSG.asmx")]
        public string WS_MiMetaBG_WsCashBVBGMail_BG_WebServiceMSG {
            get {
                return ((string)(this["WS_MiMetaBG_WsCashBVBGMail_BG_WebServiceMSG"]));
            }
        }
    }
}
